apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  REDIS_ADDR: {{ .Values.secrets.redisAddr | quote }}
  REDIS_TLS: {{ .Values.secrets.redisTls | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  RABBITMQ_URI: {{ .Values.secrets.rabbitmqUri | quote }}
  USER_SERVICE_ADDR: {{ .Values.secrets.userServiceAddr | quote }}