apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secrets
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  RABBITMQ_URI: {{ .Values.secrets.rabbitmqUri | quote }}